# Generated by Django 4.1 on 2022-09-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='blog',
        ),
    ]
